name: hw07
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - ipykernel=6.13.0 
  - pandas=1.4.2
  - matplotlib=3.5.1
  - scikit-learn=1.0.2
  - pip=22.0.4
  - pip:
    - -r requirements.txt